### PR TITLE
Greg login bug

### PR DESCRIPTION
**Pull request by gregsim92**
Fixed login bug. The problem is on app/views/index.html.erb line 12.

the time_ago_in_words function tries to interpret the value of `created_at` for each quote in the quotes table. When there is a null value in the cell, it can't be interpreted and creates the bug. 

For now I created a catch, if there is a null value, call Time.now instead, and added a test file in the spec/feature folder. 

Is there any way I can prevent a quote from being inserted into the database without a timestamp? 

EDIT (3:30 PM): removed catch from app/views/index.html.erb line 12, updated db/production.sql to set new timestamp on the previously null `created_at` cells

### CODE REVIEW

**Comment by harms280** [comment]
Hey Greg,

  Thanks for working on this!  Sounds like you pinned down the problem and made the right decision in changing the production.sql so that there are no nil values for the created_at column for those two quotes. Would you also be able to make sure the updated_at values are also not a null value? Lastly, there most definitely is a way to prevent a Quote from being created in the db if it does not have a timestamp. If you could check that the Quote model validates that the value of presence of created_at and updated_at is not nil, that would be great.

Thanks!

**Comment by gregsim92** [comment]
Ok, so I updated production.sql and removed all null value cells, tests still successfully run. Also, earlier I updated the version of rake in gemfile.lock, but since then I have reverted it back to 10.3.2.

**Comment by gregsim92** [comment]
Hey Aaron,

I made the requested changes to my pull request. Let me know if this meets the requirements

-Greg

**Comment by gregsim92** [comment]
finalized quotes validation, no null values allowed in table
edit: removed `is_complete` from quotes model

**Comment by harms280** [comment]
Looks great. Merging now.

**Pull request closed without merging**
